version: "3"

services:
  vote:
    image: dockersamples/examplevotingapp_vote:dotnet-nanoserver-sac2016
    build: 
      context: ./app1
    ports:
      - "5000:5000"


  result:
    image: dockersamples/examplevotingapp_result:dotnet-nanoserver-sac2016
    build: 
      context: ./app2
    ports:
      - "5001:5001"
 
  postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=productDb
        ports: 
            - "5432:5432"
        restart: always
        volumes: 
            - database-data:/var/lib/postgresql/data/

  pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
    pgadmin:



