version: "3"

services:
  vote:
    image: dockersamples/examplevotingapp_vote:dotnet-nanoserver-sac2016
    build: 
      context: ./app1
    ports:
      - "5000:5000"


  result:
    image: dockersamples/examplevotingapp_result:dotnet-nanoserver-sac2016
    build: 
      context: ./app2
    ports:
      - "5001:5001"
